set ruler
syntax on

let mapleader = ","

call matchadd('colorColumn', '\%81v', 100)
highlight colorColumn ctermbg=grey

noremap <c-l> :set nu! <CR>
noremap <leader><c-l> :set rnu! <CR>

nnoremap <leader><c-u> <esc>viwU

nnoremap <leader>ev :vsplit $MYVIMRC<cr>
nnoremap <leader>sv :source $MYVIMRC<cr>

nnoremap <leader>r :set rnu<cr>

vnoremap <leader>' <esc>`>a'<esc>`<i'<esc>
vnoremap <leader>" <esc>`>a"<esc>`<i"<esc>

nnoremap H ^
nnoremap L $
inoremap jk <esc>

